import './js/main'
import './js/mobile-nav'
import './js/header-slider'
import './js/projects-slider'
import './js/testimonials-slider'

import './scss/main.scss'
import './scss/header.scss'
import './scss/about-us.scss'
import './scss/services.scss'
import './scss/projects.scss'
import './scss/testimonials.scss'
import './scss/info.scss'
import './scss/footer.scss'
import './scss/footer.scss'
